Add class: Post, Employee, Main.
Vamproical/HWSprint2 pull request #1
Opened 2022-05-17 02:27 UTC by Vamproical

Create methods: fill(), read(File file), parse(String employee), print(List<Employee> employees)
Write some tests

2022-05-17 12:00 UTC, mv-shallow requested changes

2022-05-18 03:46 UTC, Vamproical commented
Внёс требуемые изменения

2022-05-18 07:56 UTC, progressicu requested changes

2022-05-18 07:56 UTC, progressicu commented on src/main/java/com/ws/hw1/Main.java
> +            System.out.println(e.getMessage());
для этого есть e.printStackTrace().
Ну допустим здесь была ошибка, мы написали в лог и дальше что, пойдем дальше выполнять? Мне кажется это немного странным

2022-05-18 07:56 UTC, progressicu commented on src/main/java/com/ws/hw1/Main.java
> +            Collections.sort(empl.getCharacteristics());
а зачем тут сортируешь? Ты же это ниже при парсинге сделал

2022-05-20 05:40 UTC, Vamproical commented on src/main/java/com/ws/hw1/Main.java
> +            Collections.sort(empl.getCharacteristics());
Убрал лишнюю сортировку

2022-05-20 05:41 UTC, Vamproical commented on src/main/java/com/ws/hw1/Main.java
> +            System.out.println(e.getMessage());
Как лучше тогда обрабатывать ошибку?

2022-05-21 04:52 UTC, progressicu commented on src/main/java/com/ws/hw1/Main.java
> +            System.out.println(e.getMessage());
https://www.baeldung.com/java-exceptions
есть много разных способов, всё зависит от ситуации. В данном случае можно было просто обернуть её в RuntimeException с человекочитаемым сообщением и кинуть дальше. В таком случае и программа остановится и более менее нормальное описание ошибки выведится

2022-05-21 04:56 UTC, progressicu approved these changes

2022-05-21 05:34 UTC, merged