Added Post\Employee controller, dtos, arguments, apiHandlerException …
Vamproical/HWSprint2 pull request #3
Opened 2022-06-06 04:56 UTC by Vamproical

Добавил контроллеры, дто, apiHandlerException. В скором времени добавлю интеграционные тесты.

2022-06-09 04:35 UTC, mv-shallow requested changes

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/EmployeeController.java
> +    public EmployeeDto addNewEmployee(@RequestBody CreateEmployeeDto employeeDto) {
Valid

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/action/AddEmployeesAction.java
> +            //employees.add(employeeMapper.toEmployee(fromFile, postService.getPost(fromFile.getPostId())));
Зачем это здесь? Такие комменты на ПР не выносим. Если действие не нужно, то можно просто удалить его

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/EmployeeController.java
> +        Employee newEmployee = employeeService.create(createEmployeeArgumentAction.execute(employeeDto));
Создание аргумента можно вынести в отдельную строку

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/action/CreateEmployeeArgumentAction.java
> +        return CreateEmployeeArgument.builder()
Действие получилось несколько избыточным. Чтобы оправдать создание действия нужно наличие какой-то логики, а здесь получение и маппинг. Можешь внести сюда создание сотрудника и возвращать сразу Employee или EmployeeDto

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/EmployeeController.java
> +    public EmployeeDto updateEmployee(@PathVariable UUID id, @RequestBody @Valid CreateEmployeeDto employeeDto) {
Отдельный DTO на обновление

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/EmployeeController.java
> +        Employee updatedPost = employeeService.update(id, createEmployeeArgumentAction.execute(employeeDto));
Действие соответственно тоже отдельное

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/PostController.java
> +    public PostDto addNewPost(@RequestBody CreatePostDto postDto) {
Valid?

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/controller/PostController.java
> +    public PostDto addNewPost(@RequestBody CreatePostDto postDto) {
В принципе, здесть комментарии по аналогии с EmployeeController

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/mapper/EmployeeMapper.java
> +@Mapper(componentModel = "spring")
Для чего задаешь модель?

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/model/Employee.java
> +    private UUID id;
Разве эти аннотации работают здесь? Более того, зачем они в модели?

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeService.java
> +public interface EmployeeService {
NonNull можно прописывать сразу в интерфейсе(и желательно для каждого аргумента метода), они перенесутся в имплементацию

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +    private Employee createEmployee(UUID id, CreateEmployeeArgument employeeArgument) {
Это уже лишнее, ведь есть builder

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +        throwExceptionIfNotExits(id);
Переиспользуй код - можно получить через готовый метод, а обновление записи сделать через сеттеры

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +        throwExceptionIfNotExits(id);
Т.к. удаление физическое(объект удаляется из коллекции), можно не делать проверку на его существование

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +    private void throwExceptionIfNotExits(UUID id) {
Можно не выносить проверку в отдельный метод. Если по ключу в map null, то кидай исключение

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +                    employee.getLastName().toLowerCase().contains(params.getName().toLowerCase()));
Можнл вынести в отдельный метод, который принимает две строки и приводит их к одному регистру + проверяет вхождение

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/SearchParams.java
> +public class SearchParams {
А не многовато аннотаций? Тут хватит и Value с Builder(можно только Value)

2022-06-09 04:35 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/post/PostServiceImpl.java
> +public class PostServiceImpl implements PostService {
Аналогичные комментарии

2022-06-09 04:35 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
> +    void get() {
А act и assert?

2022-06-09 04:35 UTC, mv-shallow commented on src/test/java/com/ws/hw1/action/AddEmployeesActionTest.java
> +class AddEmployeesActionTest {
Если тут ничего не происходит, то для чего оставил сам файл?

2022-06-09 04:35 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
> +        Assertions.assertEquals(createDto.getName(), postDto.getName());
У тебя Data над PostDto, так что можно сравнивать объекты полностью

2022-06-09 04:35 UTC, mv-shallow commented on src/test/java/com/ws/hw1/service/ParseServiceImplTest.java
> +    public static final EmployeeFromFile EMPLOYEE_FROM_FILE1 = new EmployeeFromFile(
Давай такие тестовые данные брать из json в ресурсах

2022-06-09 04:35 UTC, mv-shallow commented on src/test/java/com/ws/hw1/service/PostServiceTest.java
> +    @Test
Тесты по AAA

2022-06-09 05:24 UTC, mv-shallow commented
По организации файлов :
- сервисы внутри пакета сервисов должны быть разделены по сущности(т.е. EmployeeService и PostService в отдельных пакетах);
- контроллеры тоже следует располагать в разных пакетах;
- мапперы рядом с контроллерами в отдельных пакетах;
- когда аргументов несколько, то их стоит положить в один пакет argument(s). Сам пакет следует располагать как можно ближе к классу, который использует данные аргументы.

2022-06-11 13:15 UTC, mv-shallow commented on src/main/java/com/ws/hw1/mapper/EmployeeMapper.java
> +@Mapper(componentModel = "spring")
UPD: моё упущение, у нас в проектах это задается в pom.
                    <compilerArgs>
                        <compilerArg>-Amapstruct.defaultComponentModel=spring</compilerArg>
                    </compilerArgs>

2022-06-21 13:58 UTC, Vamproical commented
Добавил интеграционные тесты, исправил код в соответствие с комментариями выше.

2022-06-26 15:46 UTC, mv-shallow requested changes
Пакеты в lowercase(это я про exceptionHandler)

2022-06-26 15:46 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
> +        assertEqualsEmployeeDtoAndEmployee(employeeDto, employee);
Должно быть сравнение DTO с DTO. Ожидаемые данные задаются программистом, а не берутся из теста(здесь ты в качестве эталона берешь объект класса Employee, но если произошла непреднамеренная модификация, то она будет и в ответе на запрос, и в "эталоне" - ошибка упущена

2022-06-26 15:46 UTC, mv-shallow commented on src/main/java/com/ws/hw1/exceptionHandler/ApiExceptionHandler.java
> +                "The specified id is not found", new HttpHeaders(), HttpStatus.NOT_FOUND);
Советую добавить класс ErrorDto, пускай пока с одним полем. Если бы у проекта был фронтенд, то при изменении полей класс легче поддерживать. Да и ошибка редко ограничивается одним сообщением

2022-06-28 04:12 UTC, mv-shallow commented on src/main/java/com/ws/hw1/model/Employee.java
> +    private UUID id;
Прошу прощения, поторопился.  В целом, можно(и желательно) оставить аннотации по валидации для модели и аргументов, поскольку есть возможность внесения записей из файла. Если они были написаны ранее, то их можно вернуть через ПКМ в классе -> git -> show history, а там уже через GUI можно вернуть изменения.

2022-07-01 06:27 UTC, Vamproical commented
Исправил код по описанным комментариям.

2022-07-01 09:03 UTC, mv-shallow requested changes

2022-07-01 09:03 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/post/PostServiceImpl.java
> +        Guard.check(posts.containsKey(id), "The post id not found");
Не найдена должность, а не её идентификатор

2022-07-02 03:18 UTC, Vamproical commented
Изменил сообщение об ошибка, добавил ErrorDto, убрал рабочий код для тестов, CreateEmployeeDto  получаю из файла.

2022-07-03 13:30 UTC, progressicu reviewed
👍 
Правь замечания и сливаем

2022-07-03 13:30 UTC, progressicu commented on src/main/java/com/ws/hw1/controller/employee/dto/ContactsDto.java
> +    @Pattern(regexp = "^(.+)@(\\S+)$")
Есть аннотация '@Email'

2022-07-03 13:30 UTC, progressicu commented on src/main/java/com/ws/hw1/model/Employee.java
> +    private UUID id;
К разговору, что вносятся записи из файла. По идее между этим внесением есть также аргументы, которые и стоит валидировать, так что в модели можно и без валидации

2022-07-03 13:30 UTC, progressicu commented on src/main/java/com/ws/hw1/parser/EmployeeFromFile.java
> +    @NonNull
Не путай NonNull и NotNull. Нужно последнее

2022-07-03 13:30 UTC, progressicu commented on src/main/java/com/ws/hw1/parser/ParserFromJson.java
> +    public List<EmployeeFromFile> parse(File file) {
Давай на objectMapper передаелаем. Зачем нам лишний код/зависимости

2022-07-03 13:30 UTC, progressicu commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
> +        when(postService.create(postArgument)).thenReturn(post);
а зачем? В интеграционных тестах ты проверяешь микросервис полностью от и до. Моки идут в крайних случаях (о таких случаях будем говорить дальше на занятиях) и это явно не сейчас.
Так что надо это переделать

2022-07-03 14:13 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
> +        when(postService.create(postArgument)).thenReturn(post);
@Vamproical, в таком случае есть как минимум два варианта:
1) Сервис внедряется в поле класса, создается отдельный метод в данном классе, в котором через service.create добаляется сотрудник, потом через service.getAll получаем список сотрудников и берем id первого сотрудника - его и используем в тестах на update/get/... ;
2) Переделать коллекцию сотрудников на бин: Добавить класс AppConfig(конфигурация), в нем в качестве бина создать Map и внедрять ее в сервисе, тогда для тестов можно создать тестовую конфигурацию, в которой эта коллекция будет заполняться вручную.

2022-07-04 09:32 UTC, Vamproical commented
Переделал тесты, переделал запись на objectMapper.

2022-07-04 11:41 UTC, merged

2022-07-07 12:15 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
> +        PostDto expected = new PostDto(id, "Tech Writer");
Можно было и null, expected не создается в блоке Arrange