Dev branch
Vamproical/HWSprint2 pull request #4
Opened 2022-07-15 10:14 UTC by Vamproical

Добавил логгирование и интеграционные тесты с тестированием репозитория. 
В логах записывается IP и есть возможность отключить логгирование в application.properties для этого нужно раскомментировать строку !logging.level.root=OFF.

2022-07-18 12:41 UTC, mv-shallow requested changes

2022-07-18 12:41 UTC, mv-shallow commented on src/main/java/com/ws/hw1/logging/Logging.java
> +    private void saveLog(ProceedingJoinPoint joinPoint) {
Много всего в одном методе, разбей его

2022-07-18 12:41 UTC, mv-shallow commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
Через переменные окружения

2022-07-18 12:41 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
>          UUID id = UUID.randomUUID();
Лишнее

2022-07-18 12:41 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
>      void tryGetAndGetNotFound() {
Эти тесты скорее избыточны. По сути, здесь ты проверяешь не контроллер, а метод getExisting и обработчик исключений. Если и оставлять, то:
1) DataSet не нужен, база может быть и пустой.
2) Ожидаемые данные не должны быть в блоке Arrange, они не нужны для успешного вызова тестируемой функциональности

2022-07-18 12:41 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
> +                                                                                                             .getClassLoader()
Это можно вынести в утилитарный метод и использовать в тестах. Для чего создаешь файл? Есть вариант попроще/покороче

2022-07-18 12:41 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
> +        EmployeeDto expected = new EmployeeDto(UUID.fromString("720eb7c5-b0b1-4a33-ae68-4d0d5feab2d6"),
Вот это лучше в json - тут много текста, а он не так важен для понимания теста.

2022-07-18 12:41 UTC, mv-shallow commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
>      void getAllFilterByFirstName() {
Тесты на поиск лучше делать параметризованными https://www.baeldung.com/parameterized-tests-junit-5

2022-07-18 13:25 UTC, progressicu commented on src/main/java/com/ws/hw1/logging/Logging.java
> +        HttpServletRequest request = ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();
эту и 4 строки ниже можно вынести в отдельный метод. Как и в принципе вообще весь этот метод разбить по частям

2022-07-18 13:25 UTC, progressicu commented on src/main/java/com/ws/hw1/model/Employee.java
> +    @Id
Можно просто @Id, @GeneratedValue и всё

2022-07-18 13:25 UTC, progressicu commented on src/main/resources/application.properties
> +spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
а для чего это?

2022-07-18 13:25 UTC, progressicu commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
> +                                                                                                             .getClassLoader()
в сторону ClassPathResource копай

2022-07-18 13:31 UTC, progressicu commented
> Добавил логгирование и интеграционные тесты с тестированием репозитория. В логах записывается IP и есть возможность отключить логгирование в application.properties для этого нужно раскомментировать строку !logging.level.root=OFF.

Не, так не пойдет. Так ты выключаешь всё логгирование, а это плохо. Вдруг я захочу выключить только логирование изменений сущности - лучше сделать через отдельную проперть и @ConditionalOnProperty

2022-07-19 10:48 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
>      public Employee create(@NonNull CreateEmployeeArgument employeeArgument) {
UPD: в простых случаях(создание, ...), можно без транзакций

2022-07-19 10:49 UTC, mv-shallow commented on src/main/java/com/ws/hw1/logging/Logging.java
> +    public void applicationPackagePointcut() {
Меня поправил коллега: такой подход допустим, когда нужно покрыть большое количество классов. 

Но я бы всё равно добавил хотя бы коммент в readme о том, что есть логирование там-то, реализовано через аспект

2022-07-19 10:51 UTC, mv-shallow commented on src/main/java/com/ws/hw1/logging/Logging.java
> +    public void applicationPackagePointcut() {
И еще одно замечание, которое я вчера не написал, а сегодня мне о нём напомнили: надо разделить класс на два, поскольку сейчас в одном классе 2 разных логирования - и по области действия, и по логике. Подсказка к разделению тоже была в задании(независимое отключение/включение логов)

2022-07-20 03:32 UTC, snusmum commented on src/main/java/com/ws/hw1/logging/Logging.java
> +    public void applicationPackagePointcut() {
И поинткатам лучше давать более детализированные названия, соответствующие области применения.
В данном случае подошёл бы apiPointcut или controllerPointcut.

2022-07-20 03:38 UTC, snusmum commented on src/main/java/com/ws/hw1/logging/Logging.java
> +        UpdateEmployeeArgument argument = action.execute((UpdateEmployeeDto) fields[1]);
Как было сказано выше, необходимо разделить логгирование запросов и факта обновления сотрудников.
Перовое логично как и сейчас применять ко всем метода пакета.
А второе гораздо удобнее через аннотацию над методом сервиса, который выполняет обновление.
При этому, если на метод сервиса будет помечен `@Transactional`, то и код аспекта будет выполняться внутри транзакции.

2022-07-20 03:40 UTC, snusmum commented on src/main/java/com/ws/hw1/logging/Logging.java
> +                                           .build();
Создавать обновляемого сотрудника - перебор. 
Если сделать персональную аннотацию методу обновления, то можно получить сотрудника "до обновления", а после выполнения метода сравнить его с возвращаемым результатом, который и будет обновлённым сотрудником.

2022-07-20 03:43 UTC, snusmum commented on pom.xml
> +            <version>0.4</version>
scope должен быть test.
Как следствие, DiffUtils из testcontainers станут недоступны в основном приложении. Придётся искать другой способ сравнения.

2022-07-23 07:11 UTC, Vamproical commented
Разделил логгирование на два класса, добавил Property для вкл\откл логгирования действий контроллера или обновлений сотрудника.
Улучшил тесты.

2022-07-23 07:12 UTC, Vamproical commented on src/main/java/com/ws/hw1/exceptionhandler/ErrorDto.java
>  @Jacksonized
Заменил на SuperBuilder, иначе парсер не сработает

2022-07-23 07:13 UTC, Vamproical commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +        getExisting(id);
Оставил, чтобы выдавало NotFoundException исключение

2022-07-23 07:13 UTC, Vamproical commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +        return repository.findAll()
Поправил

2022-07-23 07:13 UTC, Vamproical commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
Вынес в переменные окружения

2022-07-23 07:13 UTC, Vamproical commented on src/test/java/com/ws/hw1/controller/PostControllerIT.java
>      void tryGetAndGetNotFound() {
Да, согласен, оставил один тест для проверки.

2022-07-23 07:14 UTC, Vamproical commented on src/test/java/com/ws/hw1/controller/EmployeeControllerIT.java
> +                                                                                                             .getClassLoader()
Вынес в утилитарный класс. Для единообразия всё, что касается тестов - храню в файлах, так удобнее и проще, как мне кажется

2022-07-23 07:14 UTC, Vamproical commented on src/main/java/com/ws/hw1/model/Employee.java
> +        return getClass().hashCode();
Исправил

2022-07-23 07:15 UTC, Vamproical commented on src/main/resources/application.properties
> +spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
Снова проблемы со сваггером, без этого не запускается контекст

2022-07-27 13:03 UTC, mv-shallow requested changes

2022-07-27 13:03 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeService.java
> +    @Transactional
Здесь(в интерфейсе) нет смысла ставить даную аннотацию

2022-07-27 13:03 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +    @Transactional
А уровень изоляции?

2022-07-27 13:03 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +        JPAQuery<Employee> query = jpaQueryAction.execute();
Не, можно иначе https://habr.com/ru/post/344450/
Тебя должен интересовать конец статьи. Кратко: надо унаследоваться от QueryDslPredicateExecutor, ограничения также задаются через QEmployee. Потом ты все условия сохраняешь в предикат(Predicate из querydsl) и вызываешь repository.findAll(predicate)
Еще статья(даже получше): https://www.logicbig.com/tutorials/spring-framework/spring-data/query-dsl-basic.html

2022-07-28 21:20 UTC, Vamproical commented on src/main/java/com/ws/hw1/model/Employee.java
> +    public boolean equals(Object o) {
Переопределял для старого метода логгирования с использование Diffable, в статье описаны различные способы переопределения. 
Попробовал переопределить на основе статьи, или я что-то не так понял и лучше убрать?

2022-07-29 06:45 UTC, mv-shallow commented on src/main/java/com/ws/hw1/model/Employee.java
> +    public boolean equals(Object o) {
Где в статье сказано, что в сравнении участвуют все атрибуты?

2022-07-29 06:45 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +                                                     employee.lastName.asc(),
Сортировку можно задать через Sort или Pageable, здесь лучше Sort, т.к. список. Лучше сразу из контроллера получать Sort/передавать сортировку в запросе( есть аннотация SortDefault и через нее можно указать эту сортировку)

2022-07-29 06:45 UTC, mv-shallow commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
>          QEmployee employee = QEmployee.employee;
Этот объект можно сделать полем класса

2022-07-29 20:29 UTC, Vamproical commented on src/main/java/com/ws/hw1/service/employee/EmployeeServiceImpl.java
> +                                                     employee.lastName.asc(),
Поправил

2022-07-29 20:30 UTC, Vamproical commented
Из equals убрал все поля, так как ранее использовались для Diffable

2022-08-15 08:00 UTC, merged